const ACTIONS = {
    GET_ENVOY_STRUCTURE: Symbol('GET_ENVOY_STRUCTURE'),
    GET_ENVOY_STRUCTURE_SUCCESS: Symbol('GET_ENVOY_STRUCTURE_SUCCESS'),
    ADD_ENVOY: Symbol('ADD_ENVOY'),
    ADD_ENVOY_SUCCESS: Symbol('ADD_ENVOY_SUCCESS'),
    HIDE_NOFITY: Symbol('Hide_NOFITY'),
    DISPLAY_NOFITY: Symbol('DISPLAY_NOFITY'),
    GET_MEPS: Symbol('GET_MEPS'),
    GET_MEPS_SUCCESS: Symbol('GET_MEPS_SUCCESS'),
    GET_ENVOY: Symbol('GET_ENVOY'),
    GET_ENVOY_SUCCESS: Symbol('GET_ENVOY_SUCCESS'),
    UPDATE_ENVOY: Symbol('UPDATE_ENVOY'),
    UPDATE_ENVOY_SUCCESS: Symbol('UPDATE_ENVOY_SUCCESS')
};

export default ACTIONS;